name: CI - Server
on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "**"

jobs:
  check-aplication:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Clean install dependencies
        run:  bun test

      - name: Clean install dependencies
        run: bun install

      - name: Lint
        run: bun run lint
        working-directory: ./
