name: CI - Server

on:
  push:
    paths:
      - "./"
    branches:
      - Development
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "./"
    branches:
      - "**"

jobs:
  check-aplication:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      -name: Go test
        run: bun test

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Clean install dependencies
        run: bun install

      - name: Lint
        run: bun run lint
        working-directory: ./
