name:  CI - Server

on:
  push:
    paths:
      - 'apps/server/**'
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'apps/server/**'
    branches:
      - '**'
  schedule:
    - cron: '16 14 * * 5'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Setup node env
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Run lint
      run: npm run lint:fix