name: Semantic PR Titles

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: 
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          requireScope: false
          subjectPattern: ^(\[[a-z\-]+(, [a-z\-]+)*\] )?[a-z].+[^\.]$
          subjectPatternError: 
            The "subject" must start with a lower-case letter and must not
            end with a full-stop.
            For PRs that add or change ESLint-plugin rules, you should begin
            the title with "[rule-name] "